spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri:
            http://localhost:8090/
          predicates:
            - Path= /acheteurs/**
        - id: r2
          uri:
            http://localhost:8091/
          predicates:
            - Path= /produits/**